---
- name: Deploy EpicBook Application
  hosts: epicbook_servers
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create application directory
      file:
        path: /opt/epicbook
        state: directory
        mode: '0755'

    - name: Create log directory
      file:
        path: /var/log/epicbook
        state: directory
        mode: '0755'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
